import java.util.Scanner;

/**
 * geeksforgeeks
 * Print all subsequences of a string
 * Given a string, we have to find out all subsequences of it.
 * A String is a subsequence of a given String, that is generated by deleting some character of a given string without changing its order.
 * <p>
 * Input : abc
 * Output : a, b, c, ab, bc, ac, abc, ""
 * <p>
 * Input : aaa
 * Output : a, aa, aaa, ""
 */
/* This solution works only if the input string has distinct characters */

public class AllSubsequences {
    public static void main(String[] args) {
        Scanner scanner = new Scanner(System.in);
        String input = scanner.next();
        printSubsequences(input, "");
    }

    private static void printSubsequences(String prefix, String suffix) {
        if (prefix.length() == 0) {
            System.out.println(suffix);
            return;
        }
        char c = prefix.charAt(0);
        String restOfString = prefix.substring(1);

        printSubsequences(restOfString, suffix + c);
        printSubsequences(restOfString, suffix);
    }
}